language: java

jdk:
   #- oraclejdk9
   - openjdk8

#addons:
#   sonarcloud:
#      organization: "akatsuki"
#      token:
#         secure: "" # encrypted value of your token


script:
  - ant build
  #- sonar-scanner
