language: java

jdk:
   - oraclejdk9
   - openjdk8

addons:
   sonarcloud:
      organization: "akatsuki"
      token:
         secure: "f09aa6e3e8d7d11ad0cb244c06675ba2ed721c5b" # encrypted value of your token


script:
  #- ant build
  - sonar-scanner -X
